name: Pull Request Workflow

on:
  push:
    branches: 
      - '**'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./
        run: npm install
        

      - name: Run Tests
        working-directory: ./
        run: npm run test

      - name: Echo Completion
        run: echo "Test workflow completed successfully."
